# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disp2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sq


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ttext = QtWidgets.QTextEdit(self.centralwidget)
        self.ttext.setGeometry(QtCore.QRect(160, 60, 781, 441))
        self.ttext.setObjectName("ttext")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(450, 530, 211, 51))
        self.btn.setObjectName("btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.all_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn.setText(_translate("MainWindow", "Все"))

    def all_functions(self):
        self.btn.clicked.connect(self.data)

    def data(self):
       a = ""
       with sq.connect("newdb.db") as con:
            cur = con.cursor()
   
            cur.execute("SELECT rowid, new_apart, cost_apart FROM apart")
            text1 = ""
            new_info = "new info "
            for i in cur:
                a = a + "\n" + "__________________" + "\n" + ('\n'.join(map(str, i)))
       self.ttext.setText(a)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
