# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gg.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sq

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 233)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        #Задаем цену от
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 50, 151, 21))
        self.input.setText("")
        self.input.setObjectName("input")
        
        #Задаем цены до
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 90, 151, 21))
        self.output.setText("")
        self.output.setObjectName("output")
        
        #Окно вывода
        self.Export = QtWidgets.QTextEdit(self.centralwidget)
        self.Export.setGeometry(QtCore.QRect(180, 20, 531, 171))
        self.Export.setObjectName("Export")
        
        #Кнока показа результата
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(10, 150, 151, 41))
        self.Enter.setObjectName("Enter")
        self.Enter.clicked.connect(self.price)
        
        #Подпись input
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 151, 21))
        self.label.setObjectName("label")
        
        #Подпись output
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 151, 21))
        self.label_2.setObjectName("label_2")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def price(self):
        res=""
        
        v= "Fridge == 1"
        a = self.input.text() #Смотри какую цену ввел поьзователь от
        b = self.output.text() #Смотри какую цену ввел поьзователь до
        
        with sq.connect("newdb.db") as con:
            cur = con.cursor()
            
            price = f"({a} < cost_apart AND cost_apart < {b})" # Формируем строку, которую "создал" пользователь
        
            l = "SELECT new_apart, cost_apart FROM apart WHERE " + v + " AND" + price #Формируем вывод в sql
            print(l)
            
            cur.execute(f"{l}") #Проходимся по Бд
            
            for i in cur:
                res = res + "\n" + "__________________" + "\n" + ('\n'.join(map(str, i)))
                
        self.Export.setText(res) #Выводим результат
                
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Enter.setText(_translate("MainWindow", "Найти"))
        self.label.setText(_translate("MainWindow", "Цена от:"))
        self.label_2.setText(_translate("MainWindow", "Цена до:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
